<a href="https://colab.research.google.com/github/retazo0018/Deep-Learning/blob/master/tensorflowscratchbook1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import package


In [2]:
import tensorflow as tf
import numpy as np

# Tensorflow basics:
1. Constants
2. Placeholders
3. Variables

### TF Constant

In [3]:
# Defining Constant of string type
hello_constant =  tf.constant("Hello World!")
print(hello_constant)

Tensor("Const:0", shape=(), dtype=string)


##### Two ways to view the output of a computation

In [4]:
# Method 1
with tf.Session() as sess:
  # Run the tf.constant operation in the session
  output = sess.run(hello_constant) # decode
  print(output)

b'Hello World!'


In [51]:
# Method 2
sess = tf.Session()
sess.run(hello_constant)
sess.close()

b'Hello World!'

In [52]:
# Defining constants of float type
node1 = tf.constant(3.0, tf.float32)
node2 = tf.constant(4.0) # also tf.float32 implicitly
print(node1,node2)

sess = tf.Session()
print(sess.run([node1,node2]))
sess.close() # must to close the session

Tensor("Const_9:0", shape=(), dtype=float32) Tensor("Const_10:0", shape=(), dtype=float32)
[3.0, 4.0]


In [7]:
# Multiply 2 float constants
a = tf.constant(4.0)
b = tf.constant(6.0)
c = a*b
print(c)


sess = tf.Session()
print(sess.run(c))
sess.close()

Tensor("mul:0", shape=(), dtype=float32)


Basic Math in tensorflow

In [0]:
x = tf.add(5,2)
y = tf.multiply(2,5)
z = tf.subtract(2,3)
d = tf.divide(5,1)
# matmul - > matrix multiplication

In [0]:
tf.subtract(tf.constant(2.0),tf.constant(1)) # value_error due to not doing type casting

In [19]:
tf.subtract(tf.cast(tf.constant(2.0), tf.int32),tf.constant(1))

<tf.Tensor 'Sub_2:0' shape=() dtype=int32>

## Tensorflow placeholders
  ### A placeholder is a promise to provide a value later.

In [10]:
a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)
addernode = a+b
sess = tf.Session()
print(sess.run(addernode, feed_dict = {a: [1, 2, 3], b: [3,2,1]}))
 
sess.close()

[4. 4. 4.]


## Tensorflow variables
*  Variables allow us to add trainable parameters to a graph
* ### y = .2 + .3*x

In [12]:
W1 = tf.Variable([.5], tf.float32)
# important : need to run below code to initialize the variables()
init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)
print(sess.run(W1))
sess.close()

[0.5]


# Model

In [15]:
# A linear model example
# y = b + w*x
w = tf.Variable([0.3], tf.float32)
b = tf.Variable([-.9], tf.float32)
x = tf.placeholder(tf.float32)

linear_model = w*x + b
init = tf.global_variables_initializer()

sess = tf.Session()
sess.run(init)
print(sess.run(linear_model, {x:[1,2,3,4,5,6,7]}))
sess.close()

[-5.9999996e-01 -2.9999995e-01  5.9604645e-08  3.0000007e-01
  6.0000002e-01  9.0000010e-01  1.2000002e+00]


# Activation function

Sigmoid :
  * 1 / 1+exp(-x)

In [21]:
def sigmoid(a):
  return 1/(1+np.exp(-a))
sigmoid(.3)
a = [1,2,4,0,-6,5,-7]
for i in a:
  print(sigmoid(i))

0.7310585786300049
0.8807970779778823
0.9820137900379085
0.5
0.0024726231566347743
0.9933071490757153
0.0009110511944006454


tanh(a) = (e^a - e^-a)/e^a + e^-a

In [22]:
def tanh(a):
  return np.tanh(a)
print(tanh(.3))
for i in [-4,-2,0,1,2,4]:
  print(tanh(i))

0.2913126124515909
-0.999329299739067
-0.9640275800758169
0.0
0.7615941559557649
0.9640275800758169
0.999329299739067


Relu

In [23]:
def relu(a):
  return np.maximum(0,a)
for i in [-2,0,3,-5,1,4,2]:
  print(relu(i))

0
0
3
0
1
4
2


Softmax

In [24]:
scores = [12,8,.3]
def softmax(a):
  return np.exp(a)/np.sum(np.exp(a),axis=0)
print(softmax(scores))
print(sum(softmax(scores)))

[9.82005792e-01 1.79860635e-02 8.14457845e-06]
1.0


Combined version of all 



In [25]:
a = [.2, 1, 0, 3, -2]
sigmoid_activation = tf.sigmoid(a)
tanh_activation = tf.tanh(a)
relu_activation = tf.nn.relu(a)
with tf.Session() as sess:
  op1 = sess.run(sigmoid_activation)
  op2 = sess.run(tanh_activation)
  op3 = sess.run(relu_activation)
  print("sigmoid", op1)
  print("tanh", op2)
  print("relu", op3)

sigmoid [0.54983395 0.7310586  0.5        0.95257413 0.11920292]
tanh [ 0.19737528  0.7615942   0.          0.9950547  -0.9640276 ]
relu [0.2 1.  0.  3.  0. ]


### Truncated Normal function:
 * To generate random non extreme normally distributed values with mean 0 and sd 
 * Used to initialize weights


In [29]:
a = tf.truncated_normal([2,3])
sess= tf.Session()
print(sess.run(a))
sess.close()

[[-0.60765326  0.40921587  0.29480436]
 [-0.17153586 -1.3209767   0.7068099 ]]


# Loss function
##### loss function - MSE, crossentropy ; crossentropy mainly used in classification problems

###### cross entropy - > -sum(y*log(p))

In [32]:
w = tf.Variable([0.3], tf.float32)
b = tf.Variable([-.9], tf.float32)
x = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)

linear_model = w*x + b

#  .3 * 1 + -.3 = 0
# (0-0)^2 = 0
# 2, 3 = -1
# 3, 2 = -1
# 0
# x^2 = 2x

# sum(actual-predicted)^2

squared_delta = tf.square(linear_model - y) # y- actual value, linear_model - predicted value
loss = tf.reduce_sum(squared_delta)

init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)
print(sess.run(loss, {x:[1,2,3,4], y:[0,-1,-2,-3]}))
sess.close()


15.740002


# Optimizer
##### Optimizer modifies each variable according to magnitude of the derivative of loss with respect to that variable 

In [44]:
w = tf.Variable([0.5], tf.float32)
b = tf.Variable([.1], tf.float32)
x = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)


init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)

print("Initial weight:", sess.run(w), end="; ")
print("Initial bias:", sess.run(b))

linear_model = w*x + b

squared_delta = tf.square(linear_model - y) # y- actual value, linear_model - predicted value
loss = tf.reduce_sum(squared_delta)


optimizer = tf.train.GradientDescentOptimizer(0.01)
train = optimizer.minimize(loss)

for i in range(3):
  sess.run(train, {x:[1,2,3,4], y:[0,-1,-2,-3]})


print("Optimized weight:", sess.run(w), end="; ")
print("Optimized bias:", sess.run(b))

Initial weight: [0.5]; Initial bias: [0.1]
Optimized weight: [-0.54620796]; Optimized bias: [-0.2057792]
